const data = [
  {
    projectId: 79,
    projectName: "Testing",
    epic: "Testing",
    epicId: 542,
    storyId: 1591,
    story: "first story",
    taskId: 9132,
    taskName: "test",
    columnId: 577,
    description: null,
    reporter: 344,
    createType: "ticket",
    assignee: null,
    feasibilityStatus: "Not Feasible",
    feasibilityReason: "test",
    createdAt: "2024-04-30T11:23:05.000Z",
    updatedAt: "2024-04-30T11:23:44.000Z",
    fileName: "1714476185572.docx",
    status: "To Do",
    type: "Manager",
  },
  {
    projectId: 79,
    projectName: "Testing",
    epic: "Tset",
    epicId: 640,
    storyId: 2008,
    story: "new story",
    taskId: 9131,
    taskName: "test",
    columnId: 577,
    description: null,
    reporter: 344,
    createType: "ticket",
    assignee: null,
    feasibilityStatus: "Feasible",
    feasibilityReason: null,
    createdAt: "2024-04-30T11:22:12.000Z",
    updatedAt: "2024-04-30T11:23:24.000Z",
    fileName: "",
    status: "To Do",
    type: "Manager",
  },
  {
    projectId: 79,
    projectName: "Testing",
    epic: "New Epic",
    epicId: 569,
    storyId: 3131,
    story: "hellio3",
    taskId: 9130,
    taskName: "test",
    columnId: 577,
    description: null,
    reporter: 344,
    createType: "ticket",
    assignee: null,
    feasibilityStatus: "Not Feasible",
    feasibilityReason: "test",
    createdAt: "2024-04-30T11:21:20.000Z",
    updatedAt: "2024-04-30T11:21:36.000Z",
    fileName: "",
    status: "To Do",
    type: "Manager",
  },
  {
    projectId: 108,
    projectName: "Neuvays website",
    epic: "Testing",
    epicId: 579,
    storyId: 1699,
    story: " India.neuvays.com bugs",
    taskId: 9129,
    taskName: "test",
    columnId: 744,
    description: null,
    reporter: 344,
    createType: "ticket",
    assignee: null,
    feasibilityStatus: "Feasible",
    feasibilityReason: "",
    createdAt: "2024-04-30T11:20:02.000Z",
    updatedAt: "2024-04-30T11:20:21.000Z",
    fileName: "",
    status: "To Do",
    type: "Manager",
  },
  {
    projectId: 79,
    projectName: "Testing",
    epic: "hg",
    epicId: 627,
    storyId: 3159,
    story: "first story",
    taskId: 9127,
    taskName: "test",
    columnId: 580,
    description: null,
    reporter: 344,
    createType: "ticket",
    assignee: 254,
    feasibilityStatus: "Feasible",
    feasibilityReason: "",
    createdAt: "2024-04-30T11:04:42.000Z",
    updatedAt: "2024-04-30T11:06:20.000Z",
    fileName: "",
    status: "Done",
    type: "Manager",
  },
];
function filterUniqueStatus(data) {
  const statusSet = new Set();
  const result = [];

  data.forEach((item) => {
    if (!statusSet.has(item.status)) {
      statusSet.add(item.status);
      result.push(item);
    }
  });

  return result;
}

const filteredData = filterUniqueStatus(data);
console.log(filteredData);
